### PR TITLE
Add `fnh.ngo.us`, `fannyhost.ngo.us`

### PR DESCRIPTION
**Pull request by willi-felix**
# Pull Request Template for `.ngo.us` Domain Registration

### 1. Zone File Edit

- [v] **Alphabetical Order**: Confirm your domain block is added in alphabetical order by your organization’s name.
- [v] **Two Comment Lines**: 
  - First line: Full organization name.
  - Second line: Organizational contact email (must be different from the `.ngo.us` domain applied for).
- [v] **Nameserver Entries**:
  - At least two NS (Nameserver) records with a TTL value of `86400`.
  - Correct format for the domain block (see README for examples).

Example:
```
; Happy Cat Foundation
; Submitted by networking team <happycat@example.org>
happycat 86400 IN NS ns1.example.com.
happycat 86400 IN NS ns2.example.com.
```

---

#### a. **Intended Use of Domain**

FannyHost Corporation is a free hosting service based in Southeast Asia, we provide quality hosting
The domain name fnh.ngo.us will  is used for the home page and its subdomains are used for the control panels.

#### b. **Organization Online Presence URLs for Verification**

Currently our organization does not have a domain name on the Internet.

#### c. **Proof of Domain Mention**

Link: https://i.imgur.com/OGIjuDv.jpeg

Our company and project just started so there are not many users, so there is not much reaction.
The link above is a screenshot of the announcement from the admin sent to users in the project's Discord server.

---

### 3. Agreement to Terms

By submitting this pull request, I agree to the following:
- My organization is a non-commercial entity that is not affiliated with any government body.
- My organization operates legally and in good faith according to the stated purpose.
- I have provided accurate and truthful information throughout this application.
- Other terms outlined in the Registry's [Terms of Service](https://nic.ngo.us/terms-of-service/).

---

### 4. Final Checklist Before Submitting

- [v] Zone file edited correctly, following format and alphabetical order.
- [v] At least two valid nameservers with correct TTL (86400).
- [v] Domain block includes required comments with organization name and contact email.
- [v] Intended use of the domain clearly explained.
- [v] URLs for verification included with the exact domain name mentioned on the public profile.
- [v] Agreement to terms signed.

---

### CODE REVIEW

**Comment by alstrasolutions** [comment]
@willi-felix Please fill out the "PR Description" section.

**Comment by willi-felix** [comment]
FannyHost Corporation is a free hosting service based in Southeast Asia, we provide quality hosting
The domain name fnh.ngo.us will be used free of charge for users when using the service.
The domain name fannyhost.ngo.us is used for the home page and its subdomains are used for the control panels.

Currently our organization does not have a domain name on the Internet.

Domain names will only be used for corporate purposes, do not distribute or share domain names outside of business purposes.

**Comment by alstrasolutions** [comment]
It is okay if your organization is new or has few people, as long as it meets the [Eligibility Requirements](https://github.com/ngo-us/registry?tab=readme-ov-file#eligibility-requirements). However, as you can see under the "[Public Online Presence](https://github.com/ngo-us/registry?tab=readme-ov-file#eligibility-requirements)" section, we must have something authentic to prove the existence of the nonprofit organization you described and that it is operated in an organized way to justify the ngo.us subdomain. 

In addition, your hosting service must meet the requirements outlined [here](https://github.com/ngo-us/registry?tab=readme-ov-file#eligibility-requirements), including being an established nonprofit organization, project, or initiative. Commercial activities such as paid hosting services are not permitted under the .ngo.us domains.

**Comment by alstrasolutions** [comment]
A reasonable level of proof is still required; a screenshot is not considered verifiable information.

> 2. Public Online Presence
> Applicants must maintain a visible, publicly accessible online presence that accurately reflects their organization’s work and mission. This can include a website, social media profile, or other online platforms that provide comprehensive and up-to-date information about the organization’s history, activities, and objectives. For social media profiles, the account must have at least 20 followers and a minimum of 20 posts, demonstrating ongoing engagement with the public. The account should not be brand new or created solely for the purpose of applying for a ngo.us subdomain. Similarly, if you submit a website or other type of online presence, it must be verifiable, trustworthy, and demonstrate the organization's sustained activities, not just created to meet the application criteria. Your online presence is an important factor in establishing your organization’s legitimacy and credibility. It should clearly demonstrate your long-term commitment to your mission and ongoing public engagement.

**Comment by willi-felix** [comment]
What should I do now?

But can you provide it to me. I need time to set up the website

**Comment by alstrasolutions** [comment]
Again, **please review the requirements outlined [here](https://github.com/ngo-us/registry?tab=readme-ov-file#eligibility-requirements)**. 

Having an existing dedicated website for your organization is not necessary, and please do NOT create a new website solely to bypass this review. 

What we are looking for is any verifiable evidence of your organization's existence—some examples are already listed in the eligibility requirements. It must be verifiable, trustworthy, and demonstrate the organization's sustained activities, not just created to meet the application criteria.

**Comment by willi-felix** [comment]
We have not yet reached the Nonprofit level. On behalf of the entire Organization, I am canceling this pull request.

**Pull request closed without merging**
